### ISSUE TITLE
a problem with bag_to_kitti.py

### ISSUE THREAD

**Issue by omnigeeker** [udacity/didi-competition#5]
all my files is correct, but problem

$ sudo ./run-bag_to_kitti.sh -i ~/Data/Didi/Didi-Release-2 -o ~/Data/Didi/output2

Running 'python /python/bag_to_kitti.py' with input dir '/home/elninowang/Data/Didi/Didi-Release-2', output dir '/home/elninowang/Data/Didi/output2', docker image 'udacity-sdc2017-reader'...
Extracting bag info /data/Data/2/1.bag
ERROR bag unindexed: /data/Data/2/1.bag.  Run rosbag reindex.
Traceback (most recent call last):
  File "/python/bag_to_kitti.py", line 471, in <module>
    main()
  File "/python/bag_to_kitti.py", line 258, in main
    bagsets = find_bagsets(indir, filter_topics=filter_topics, set_per_file=True, metadata_filename='metadata.csv')
  File "/python/bag_utils.py", line 169, in find_bagsets
    bag_set = BagSet(set_name, [f], filter_topics, metadata_path)
  File "/python/bag_utils.py", line 81, in __init__
    self._process_infos(filter_topics)
  File "/python/bag_utils.py", line 91, in _process_infos
    info = get_bag_info(f)
  File "/python/bag_utils.py", line 28, in get_bag_info
    if 'start' in info:
TypeError: argument of type 'NoneType' is not iterable

**Comment by omnigeeker** [comment]
i solved this problem
